//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rayshud_Installer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://837bcb9dc43d459daaaf6afbd0f6bcb0@sentry.io/1270434")]
        public string SentryIO {
            get {
                return ((string)(this["SentryIO"]));
            }
            set {
                this["SentryIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("master")]
        public string GitBranch {
            get {
                return ((string)(this["GitBranch"]));
            }
            set {
                this["GitBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CriticalFlaw/rayshud-Installer/master/rayshud-I" +
            "nstaller/settings.json")]
        public string GitSettings {
            get {
                return ((string)(this["GitSettings"]));
            }
            set {
                this["GitSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/raysfire/rayshud/master/README.md")]
        public string GitVersion {
            get {
                return ((string)(this["GitVersion"]));
            }
            set {
                this["GitVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Steam\\steamapps\\common\\Team Fortress 2\\tf\\custom")]
        public string TFDirectory {
            get {
                return ((string)(this["TFDirectory"]));
            }
            set {
                this["TFDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rayshud.zip")]
        public string TempName {
            get {
                return ((string)(this["TempName"]));
            }
            set {
                this["TempName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("settings.json")]
        public string SettingsName {
            get {
                return ((string)(this["SettingsName"]));
            }
            set {
                this["SettingsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rayshud has been installed")]
        public string SuccessInstall {
            get {
                return ((string)(this["SuccessInstall"]));
            }
            set {
                this["SuccessInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rayshud has been updated")]
        public string SuccessRefresh {
            get {
                return ((string)(this["SuccessRefresh"]));
            }
            set {
                this["SuccessRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rayshud settings applied")]
        public string SuccessUpdate {
            get {
                return ((string)(this["SuccessUpdate"]));
            }
            set {
                this["SuccessUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rayshud has been removed")]
        public string SuccessRemove {
            get {
                return ((string)(this["SuccessRemove"]));
            }
            set {
                this["SuccessRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tf/custom directory not set! Click the browse button to set it before installing")]
        public string TFDirectoryNotSet {
            get {
                return ((string)(this["TFDirectoryNotSet"]));
            }
            set {
                this["TFDirectoryNotSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to find the tf/custom directory")]
        public string TFDirectoryNotFound {
            get {
                return ((string)(this["TFDirectoryNotFound"]));
            }
            set {
                this["TFDirectoryNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to find rayshud in the tf/custom directory")]
        public string rayshudNotFound {
            get {
                return ((string)(this["rayshudNotFound"]));
            }
            set {
                this["rayshudNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to find the local version number")]
        public string ErrorVersionLocal {
            get {
                return ((string)(this["ErrorVersionLocal"]));
            }
            set {
                this["ErrorVersionLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to find the latest version number")]
        public string ErrorVersionLive {
            get {
                return ((string)(this["ErrorVersionLive"]));
            }
            set {
                this["ErrorVersionLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while attempting to download and install rayshud")]
        public string ErrorInstall {
            get {
                return ((string)(this["ErrorInstall"]));
            }
            set {
                this["ErrorInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while attempting to apply changes to rayshud")]
        public string ErrorUpdate {
            get {
                return ((string)(this["ErrorUpdate"]));
            }
            set {
                this["ErrorUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while loading installer settings")]
        public string ErrorLoad {
            get {
                return ((string)(this["ErrorLoad"]));
            }
            set {
                this["ErrorLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while attempting to remove rayshud")]
        public string ErrorRemove {
            get {
                return ((string)(this["ErrorRemove"]));
            }
            set {
                this["ErrorRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CriticalFlaw/rayshud-Installer/master/rayshud-I" +
            "nstaller/Properties/AssemblyInfo.cs")]
        public string InstallerVersion {
            get {
                return ((string)(this["InstallerVersion"]));
            }
            set {
                this["InstallerVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A new version of the installer is available on GitHub! Download it here: https://" +
            "github.com/CriticalFlaw/rayshud-Installer/releases")]
        public string InstallerUpdate {
            get {
                return ((string)(this["InstallerUpdate"]));
            }
            set {
                this["InstallerUpdate"] = value;
            }
        }
    }
}
