//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rayshud_installer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_ClassicHUD {
            get {
                return ((bool)(this["v_ClassicHUD"]));
            }
            set {
                this["v_ClassicHUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Scoreboard {
            get {
                return ((bool)(this["v_Scoreboard"]));
            }
            set {
                this["v_Scoreboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_DisguiseImage {
            get {
                return ((bool)(this["v_DisguiseImage"]));
            }
            set {
                this["v_DisguiseImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_DefaultBG {
            get {
                return ((bool)(this["v_DefaultBG"]));
            }
            set {
                this["v_DefaultBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_ClassImage {
            get {
                return ((bool)(this["v_ClassImage"]));
            }
            set {
                this["v_ClassImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_DamagePos {
            get {
                return ((bool)(this["v_DamagePos"]));
            }
            set {
                this["v_DamagePos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int v_UberAnimation {
            get {
                return ((int)(this["v_UberAnimation"]));
            }
            set {
                this["v_UberAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string v_UberBarColor {
            get {
                return ((string)(this["v_UberBarColor"]));
            }
            set {
                this["v_UberBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3219")]
        public string v_UberFullColor {
            get {
                return ((string)(this["v_UberFullColor"]));
            }
            set {
                this["v_UberFullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA500")]
        public string v_UberFlash1 {
            get {
                return ((string)(this["v_UberFlash1"]));
            }
            set {
                this["v_UberFlash1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4500")]
        public string v_UberFlash2 {
            get {
                return ((string)(this["v_UberFlash2"]));
            }
            set {
                this["v_UberFlash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int v_XHairStyle {
            get {
                return ((int)(this["v_XHairStyle"]));
            }
            set {
                this["v_XHairStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F2F2")]
        public string v_XHairBaseColor {
            get {
                return ((string)(this["v_XHairBaseColor"]));
            }
            set {
                this["v_XHairBaseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string v_XHairPulseColor {
            get {
                return ((string)(this["v_XHairPulseColor"]));
            }
            set {
                this["v_XHairPulseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_XHairEnable {
            get {
                return ((bool)(this["v_XHairEnable"]));
            }
            set {
                this["v_XHairEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_XHairOutline {
            get {
                return ((bool)(this["v_XHairOutline"]));
            }
            set {
                this["v_XHairOutline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_XHairPulse {
            get {
                return ((bool)(this["v_XHairPulse"]));
            }
            set {
                this["v_XHairPulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int v_HealthStyle {
            get {
                return ((int)(this["v_HealthStyle"]));
            }
            set {
                this["v_HealthStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string v_HealthNormal {
            get {
                return ((string)(this["v_HealthNormal"]));
            }
            set {
                this["v_HealthNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string v_HealingDone {
            get {
                return ((string)(this["v_HealingDone"]));
            }
            set {
                this["v_HealingDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string v_HealthBuff {
            get {
                return ((string)(this["v_HealthBuff"]));
            }
            set {
                this["v_HealthBuff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF9900")]
        public string v_HealthLow {
            get {
                return ((string)(this["v_HealthLow"]));
            }
            set {
                this["v_HealthLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string v_AmmoClip {
            get {
                return ((string)(this["v_AmmoClip"]));
            }
            set {
                this["v_AmmoClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#48FFFF")]
        public string v_AmmoClipLow {
            get {
                return ((string)(this["v_AmmoClipLow"]));
            }
            set {
                this["v_AmmoClipLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF2A82")]
        public string v_AmmoReserve {
            get {
                return ((string)(this["v_AmmoReserve"]));
            }
            set {
                this["v_AmmoReserve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF801C")]
        public string v_AmmoReserveLow {
            get {
                return ((string)(this["v_AmmoReserveLow"]));
            }
            set {
                this["v_AmmoReserveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_TeamCenter {
            get {
                return ((bool)(this["v_TeamCenter"]));
            }
            set {
                this["v_TeamCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_ChatBottom {
            get {
                return ((bool)(this["v_ChatBottom"]));
            }
            set {
                this["v_ChatBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_directory {
            get {
                return ((string)(this["app_directory"]));
            }
            set {
                this["app_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int v_XHairSize {
            get {
                return ((int)(this["v_XHairSize"]));
            }
            set {
                this["v_XHairSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Steam\\steamapps\\common\\Team Fortress 2\\tf\\custom")]
        public string app_directory_steam {
            get {
                return ((string)(this["app_directory_steam"]));
            }
            set {
                this["app_directory_steam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime app_hud_mod_date {
            get {
                return ((global::System.DateTime)(this["app_hud_mod_date"]));
            }
            set {
                this["app_hud_mod_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_hud_version_local {
            get {
                return ((string)(this["app_hud_version_local"]));
            }
            set {
                this["app_hud_version_local"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/raysfire/rayshud/master/README.md")]
        public string app_hud_readme {
            get {
                return ((string)(this["app_hud_readme"]));
            }
            set {
                this["app_hud_readme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_hud_version_current {
            get {
                return ((string)(this["app_hud_version_current"]));
            }
            set {
                this["app_hud_version_current"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the main menu style setting")]
        public string error_writer_main_menu {
            get {
                return ((string)(this["error_writer_main_menu"]));
            }
            set {
                this["error_writer_main_menu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the scoreboard style setting")]
        public string error_writer_scoreboard {
            get {
                return ((string)(this["error_writer_scoreboard"]));
            }
            set {
                this["error_writer_scoreboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the default background setting")]
        public string error_writer_backgrounds {
            get {
                return ((string)(this["error_writer_backgrounds"]));
            }
            set {
                this["error_writer_backgrounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the team select style setting")]
        public string error_writer_team_select {
            get {
                return ((string)(this["error_writer_team_select"]));
            }
            set {
                this["error_writer_team_select"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the health style setting")]
        public string error_writer_health_style {
            get {
                return ((string)(this["error_writer_health_style"]));
            }
            set {
                this["error_writer_health_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the disguise image setting")]
        public string error_writer_disguise_image {
            get {
                return ((string)(this["error_writer_disguise_image"]));
            }
            set {
                this["error_writer_disguise_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the uber animation setting")]
        public string error_writer_uber_animation {
            get {
                return ((string)(this["error_writer_uber_animation"]));
            }
            set {
                this["error_writer_uber_animation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the crosshair pulse setting")]
        public string error_writer_xhair_pulse {
            get {
                return ((string)(this["error_writer_xhair_pulse"]));
            }
            set {
                this["error_writer_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the class image setting")]
        public string error_writer_class_image {
            get {
                return ((string)(this["error_writer_class_image"]));
            }
            set {
                this["error_writer_class_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the chatbox position setting")]
        public string error_writer_chatbox_pos {
            get {
                return ((string)(this["error_writer_chatbox_pos"]));
            }
            set {
                this["error_writer_chatbox_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the crosshair settings")]
        public string error_writer_xhair {
            get {
                return ((string)(this["error_writer_xhair"]));
            }
            set {
                this["error_writer_xhair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the custom color settings")]
        public string error_writer_colors {
            get {
                return ((string)(this["error_writer_colors"]));
            }
            set {
                this["error_writer_colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while applying the damage position setting")]
        public string error_writer_damage_pos {
            get {
                return ((string)(this["error_writer_damage_pos"]));
            }
            set {
                this["error_writer_damage_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while saving rayshud settings")]
        public string error_app_save {
            get {
                return ((string)(this["error_app_save"]));
            }
            set {
                this["error_app_save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while loading rayshud settings")]
        public string error_app_load {
            get {
                return ((string)(this["error_app_load"]));
            }
            set {
                this["error_app_load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while installing rayshud")]
        public string error_app_install {
            get {
                return ((string)(this["error_app_install"]));
            }
            set {
                this["error_app_install"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while uninstalling rayshud")]
        public string error_app_uninstall {
            get {
                return ((string)(this["error_app_uninstall"]));
            }
            set {
                this["error_app_uninstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while resetting rayshud settings")]
        public string error_app_reset {
            get {
                return ((string)(this["error_app_reset"]));
            }
            set {
                this["error_app_reset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("An error occurred while checking the rayshud version number")]
        public string error_app_version {
            get {
                return ((string)(this["error_app_version"]));
            }
            set {
                this["error_app_version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_directory_base {
            get {
                return ((string)(this["app_directory_base"]));
            }
            set {
                this["app_directory_base"] = value;
            }
        }
    }
}
