//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rayshud_installer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_menu_classic {
            get {
                return ((bool)(this["hud_menu_classic"]));
            }
            set {
                this["hud_menu_classic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_scoreboard_minimal {
            get {
                return ((bool)(this["hud_scoreboard_minimal"]));
            }
            set {
                this["hud_scoreboard_minimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_disguise_image {
            get {
                return ((bool)(this["hud_disguise_image"]));
            }
            set {
                this["hud_disguise_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_default_backgrounds {
            get {
                return ((bool)(this["hud_default_backgrounds"]));
            }
            set {
                this["hud_default_backgrounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_menu_class_image {
            get {
                return ((bool)(this["hud_menu_class_image"]));
            }
            set {
                this["hud_menu_class_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_damage_above {
            get {
                return ((bool)(this["hud_damage_above"]));
            }
            set {
                this["hud_damage_above"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hud_uber_animation {
            get {
                return ((int)(this["hud_uber_animation"]));
            }
            set {
                this["hud_uber_animation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string hud_uber_color_bar {
            get {
                return ((string)(this["hud_uber_color_bar"]));
            }
            set {
                this["hud_uber_color_bar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3219")]
        public string hud_uber_color_full {
            get {
                return ((string)(this["hud_uber_color_full"]));
            }
            set {
                this["hud_uber_color_full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA500")]
        public string hud_uber_color_flash1 {
            get {
                return ((string)(this["hud_uber_color_flash1"]));
            }
            set {
                this["hud_uber_color_flash1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4500")]
        public string hud_uber_color_flash2 {
            get {
                return ((string)(this["hud_uber_color_flash2"]));
            }
            set {
                this["hud_uber_color_flash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hud_xhair_style {
            get {
                return ((int)(this["hud_xhair_style"]));
            }
            set {
                this["hud_xhair_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F2F2")]
        public string hud_xhair_color_base {
            get {
                return ((string)(this["hud_xhair_color_base"]));
            }
            set {
                this["hud_xhair_color_base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string hud_xhair_color_pulse {
            get {
                return ((string)(this["hud_xhair_color_pulse"]));
            }
            set {
                this["hud_xhair_color_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_xhair_enable {
            get {
                return ((bool)(this["hud_xhair_enable"]));
            }
            set {
                this["hud_xhair_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_xhair_outline {
            get {
                return ((bool)(this["hud_xhair_outline"]));
            }
            set {
                this["hud_xhair_outline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_xhair_pulse {
            get {
                return ((bool)(this["hud_xhair_pulse"]));
            }
            set {
                this["hud_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hud_health_style {
            get {
                return ((int)(this["hud_health_style"]));
            }
            set {
                this["hud_health_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string hud_health_normal {
            get {
                return ((string)(this["hud_health_normal"]));
            }
            set {
                this["hud_health_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string hud_healing_done {
            get {
                return ((string)(this["hud_healing_done"]));
            }
            set {
                this["hud_healing_done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string hud_health_buff {
            get {
                return ((string)(this["hud_health_buff"]));
            }
            set {
                this["hud_health_buff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF9900")]
        public string hud_health_low {
            get {
                return ((string)(this["hud_health_low"]));
            }
            set {
                this["hud_health_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string hud_ammo_clip {
            get {
                return ((string)(this["hud_ammo_clip"]));
            }
            set {
                this["hud_ammo_clip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF2A82")]
        public string hud_ammo_clip_low {
            get {
                return ((string)(this["hud_ammo_clip_low"]));
            }
            set {
                this["hud_ammo_clip_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#48FFFF")]
        public string hud_ammo_reserve {
            get {
                return ((string)(this["hud_ammo_reserve"]));
            }
            set {
                this["hud_ammo_reserve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF801C")]
        public string hud_ammo_reserve_low {
            get {
                return ((string)(this["hud_ammo_reserve_low"]));
            }
            set {
                this["hud_ammo_reserve_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_team_class_center {
            get {
                return ((bool)(this["hud_team_class_center"]));
            }
            set {
                this["hud_team_class_center"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_chat_bottom {
            get {
                return ((bool)(this["hud_chat_bottom"]));
            }
            set {
                this["hud_chat_bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hud_xhair_size {
            get {
                return ((int)(this["hud_xhair_size"]));
            }
            set {
                this["hud_xhair_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime app_hud_mod_date {
            get {
                return ((global::System.DateTime)(this["app_hud_mod_date"]));
            }
            set {
                this["app_hud_mod_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_hud_version_local {
            get {
                return ((string)(this["app_hud_version_local"]));
            }
            set {
                this["app_hud_version_local"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/raysfire/rayshud/master/README.md")]
        public string app_hud_readme {
            get {
                return ((string)(this["app_hud_readme"]));
            }
            set {
                this["app_hud_readme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_hud_version_current {
            get {
                return ((string)(this["app_hud_version_current"]));
            }
            set {
                this["app_hud_version_current"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_hud_directory {
            get {
                return ((string)(this["app_hud_directory"]));
            }
            set {
                this["app_hud_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/raysfire/rayshud/archive/master.zip")]
        public string app_hud_download {
            get {
                return ((string)(this["app_hud_download"]));
            }
            set {
                this["app_hud_download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Program Files\\Steam\\steamapps\\common\\Team Fortress 2\\tf\\custom")]
        public string app_tf_directory_64 {
            get {
                return ((string)(this["app_tf_directory_64"]));
            }
            set {
                this["app_tf_directory_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Program Files (x86)\\Steam\\steamapps\\common\\Team Fortress 2\\tf\\custom")]
        public string app_tf_directory_32 {
            get {
                return ((string)(this["app_tf_directory_32"]));
            }
            set {
                this["app_tf_directory_32"] = value;
            }
        }
    }
}
